-- Create favorites table
create table public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  city_name text not null,
  city_description text,
  city_rating float8,
  city_attractions int,
  city_image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.favorites enable row level security;

-- Policies for favorites
create policy "Favorites are viewable by owner"
  on favorites for select
  using ( auth.uid() = user_id );

create policy "Users can create their own favorites"
  on favorites for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own favorites"
  on favorites for delete
  using ( auth.uid() = user_id );
